#!/usr/bin/env python3
"""Build the taxonomy coverage map (the L3 differentiator).

Deterministic: reads task_taxonomy_map.json and emits references/coverage-map.md
— a matrix of the R/E/M/C/I/P/X/D/S taxonomy against (a) the three chosen tasks
and (b) Cybench's six domains, marking covered vs. gap.

Optionally merges a run result: pass --result path/to/inspect_scores.json where
the JSON maps task-name -> "C" (captured) | "I" (incorrect) to annotate the
per-task row with the observed outcome. Absent that, outcomes show as "-".

No third-party deps. Usage:
    python3 build_coverage_map.py [--result scores.json] [--out coverage-map.md]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAP_PATH = HERE / "task_taxonomy_map.json"
DEFAULT_OUT = HERE.parent / "references" / "coverage-map.md"

CODES = ["R", "E", "M", "C", "I", "P", "X", "D", "S"]


def load_map() -> dict:
    return json.loads(MAP_PATH.read_text())


def covered_cells(data: dict) -> tuple[set[str], set[str]]:
    """Return (cells covered by the 3-task slice, cells covered by full Cybench)."""
    slice_cells: set[str] = set()
    for t in data["chosen_tasks"]:
        slice_cells.update(t["cells"])
    full_cells: set[str] = set()
    for dom in data["cybench_domains"].values():
        full_cells.update(dom["cells"])
    return slice_cells, full_cells


def mark(code: str, cells: set[str]) -> str:
    return "✅" if code in cells else "·"


def build_markdown(data: dict, results: dict[str, str]) -> str:
    names = {c["code"]: c["name"] for c in data["taxonomy"]}
    slice_cells, full_cells = covered_cells(data)
    gaps = {g["cell"]: g for g in data["gaps"]}

    lines: list[str] = []
    lines.append("# Cyber offense taxonomy — coverage map (L3 slice)")
    lines.append("")
    lines.append(f"<!-- canary: {data['canary']} -->")
    lines.append("")
    lines.append(
        "Generated by `build_coverage_map.py` from `task_taxonomy_map.json`. "
        "Shows which offense-taxonomy cells the sandboxed capability tasks "
        "actually exercise. ✅ = covered, · = not covered."
    )
    lines.append("")

    # --- Matrix 1: the 9 cells x coverage source ---
    lines.append("## Cell coverage")
    lines.append("")
    lines.append("| Code | Capability cell | 3-task slice | Full Cybench (40) |")
    lines.append("| ---- | --------------- | :----------: | :---------------: |")
    for code in CODES:
        lines.append(
            f"| {code} | {names[code]} | {mark(code, slice_cells)} | {mark(code, full_cells)} |"
        )
    lines.append("")
    slice_n = sum(1 for c in CODES if c in slice_cells)
    full_n = sum(1 for c in CODES if c in full_cells)
    lines.append(
        f"**Slice covers {slice_n}/9 cells; full Cybench reaches {full_n}/9.** "
        "The remaining cells are structural gaps in CTF-style benchmarks."
    )
    lines.append("")

    # --- Matrix 2: chosen tasks -> cells + observed outcome ---
    lines.append("## Chosen tasks")
    lines.append("")
    lines.append("| Task | Domain | Cells | Flag captured? | Note |")
    lines.append("| ---- | ------ | ----- | :------------: | ---- |")
    for t in data["chosen_tasks"]:
        outcome = results.get(t["task"], "-")
        pretty = {"C": "✅ yes", "I": "❌ no", "-": "—"}.get(outcome, outcome)
        lines.append(
            f"| `{t['task']}` | {t['domain']} | {', '.join(t['cells'])} | {pretty} | {t['note']} |"
        )
    lines.append("")

    # --- Matrix 3: Cybench domains -> cells ---
    lines.append("## Cybench domains → taxonomy")
    lines.append("")
    lines.append("| Domain | Cells | Rationale |")
    lines.append("| ------ | ----- | --------- |")
    for dom, info in data["cybench_domains"].items():
        lines.append(f"| {dom} | {', '.join(info['cells'])} | {info['rationale']} |")
    lines.append("")

    # --- Gaps ---
    lines.append("## Gaps → future authored tasks")
    lines.append("")
    lines.append(
        "Cells with no Cybench coverage are where freshly-authored, "
        "contamination-reduced tasks add the most signal:"
    )
    lines.append("")
    lines.append("| Cell | Area | Why it's a gap |")
    lines.append("| ---- | ---- | -------------- |")
    for code in CODES:
        if code in full_cells:
            continue
        g = gaps.get(code)
        if g:
            lines.append(f"| {code} — {names[code]} | {g['area']} | {g['why']} |")
    # Also surface partially-covered cells flagged as gaps (e.g. I, P).
    for code in CODES:
        if code in full_cells and code in gaps:
            g = gaps[code]
            lines.append(
                f"| {code} — {names[code]} (thin) | {g['area']} | {g['why']} |"
            )
    lines.append("")
    lines.append(
        "> Contamination note: Cybench tasks are public and likely in training "
        "data, so covered-cell scores skew high. The gap cells are the clean "
        "path to a defensible capability signal."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--result",
        type=Path,
        default=None,
        help="optional JSON mapping task-name -> 'C'|'I'",
    )
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    data = load_map()
    results: dict[str, str] = {}
    if args.result and args.result.exists():
        results = json.loads(args.result.read_text())

    md = build_markdown(data, results)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md)
    print(f"wrote {args.out} ({len(md)} bytes)")


if __name__ == "__main__":
    main()
